In [27]:
# import the andes package
import andes
import pandas as pd
import numpy as np
import os

# Load case can run power flow

In [28]:
# Load case built-in in ANDES
# get case return the directory of the default cases

# load the IEEE 14-bus system
# ssa = andes.load(
#                 andes.get_case('ieee39/ieee39.xlsx'),
#                 setup=False,     # If setup=False, need to call ss.setup() before running the simulation
#                 no_output=True, 
#                 default_config=False
#             )

# Load custom case
case = '/LLM_power_flow/ieee39_base.xlsx'
dir_path = os.path.abspath('..')
case = dir_path + case
ssa = andes.load(case,
                setup=False,
                no_output=True,
                default_config=False)

In [29]:
# setup the case and call the power flow calculation
ssa.setup()
ssa.PFlow.run()

c:\users\sheb691\gitpack\andes\andes\core\model\model.py:1712: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  return numba.jit(func,


True

# Check power flow results

### Generaton output

In [30]:
# PV bus active power
ssa.PV.p.v

array([4.36086385, 6.45999998, 7.24999998, 6.51999998, 5.07999998,
       6.86999998, 5.79999998, 3.21521338, 7.64783381])

In [31]:
# PV bus reactive power
ssa.PV.q.v

array([ 0.92695784,  3.11214459,  1.49082487,  1.3004359 ,  1.45215824,
        2.25526839,  0.60708173, -0.27616911,  1.23275886])

In [32]:
# Slack bus active power
ssa.Slack.p.v

array([5.73110424])

In [33]:
# Slack bus reactive power
ssa.Slack.q.v

array([-0.29627048])

In [34]:
# Check bus voltages
ssa.Bus.v.v

array([1.04868761, 1.0477321 , 1.03027664, 1.05280207, 1.07151943,
       1.07298983, 1.05968363, 1.05699015, 1.05300459, 1.07154265,
       1.07143273, 1.06828428, 1.06704485, 1.0574795 , 1.04023868,
       1.04696619, 1.04323211, 1.03694998, 1.06446398, 1.00185704,
       1.04421028, 1.05958154, 1.05222398, 1.05124074, 1.04660429,
       1.05630551, 1.044708  , 1.05981419, 1.06071687, 1.035534  ,
       1.013246  , 1.020528  , 1.01343   , 1.019109  , 1.06      ,
       1.06      , 1.013996  , 1.052803  , 1.03      ])

In [35]:
# Check bus angles
ssa.Bus.a.v

array([-0.19998575, -0.21285548, -0.27924844, -0.27175294, -0.24593914,
       -0.2350007 , -0.26426323, -0.26966311, -0.22415872, -0.20072272,
       -0.21400762, -0.23701408, -0.21446685, -0.24189129, -0.25106413,
       -0.22839431, -0.2529314 , -0.27028396, -0.14639119, -0.17027505,
       -0.18305282, -0.10248965, -0.10594027, -0.2251349 , -0.21040457,
       -0.23630815, -0.26391678, -0.18981154, -0.14700679, -0.13821682,
       -0.11759567, -0.05836354, -0.05533608, -0.08108323, -0.01271368,
        0.03570424, -0.13813676, -0.0381907 , -0.19128809])

### Branch flow

In [36]:
# Check branch power flows
# 
ssa.Line.a1.e

array([ 0.34381385, -0.34381385,  4.82481624, -0.12051495, -0.44644419,
       -0.75738392, -2.3599496 , -2.58811706, -4.85276837,  2.48745875,
        3.70494519, -2.90182363,  1.35882306, -1.37985113, -1.38388473,
        3.52117978,  3.72881967,  3.13240841,  0.53120366, -2.67027621,
        3.0296565 , -4.71097304, -3.64018909, -0.64487639,  2.34196361,
        0.68179501, -6.39005206,  0.44978615,  3.75921493,  0.8481739 ,
        2.1350464 , -1.09353379, -1.58587762, -3.15815058, -4.36086366,
        5.65999998, -7.24999945, -0.60916372, -0.59083628,  1.74631493,
       -6.48987311, -5.0558094 , -6.86999951, -5.78486593, -3.20913626,
       -7.60452084])

In [37]:
ssa.Line.a1.e.shape

(46,)

In [38]:
ssa.Line.get(src='a1', 
            idx= ssa.Line.idx.v, 
            attr='e')

array([ 0.34381385, -0.34381385,  4.82481624, -0.12051495, -0.44644419,
       -0.75738392, -2.3599496 , -2.58811706, -4.85276837,  2.48745875,
        3.70494519, -2.90182363,  1.35882306, -1.37985113, -1.38388473,
        3.52117978,  3.72881967,  3.13240841,  0.53120366, -2.67027621,
        3.0296565 , -4.71097304, -3.64018909, -0.64487639,  2.34196361,
        0.68179501, -6.39005206,  0.44978615,  3.75921493,  0.8481739 ,
        2.1350464 , -1.09353379, -1.58587762, -3.15815058, -4.36086366,
        5.65999998, -7.24999945, -0.60916372, -0.59083628,  1.74631493,
       -6.48987311, -5.0558094 , -6.86999951, -5.78486593, -3.20913626,
       -7.60452084])

In [39]:
ssa.Line.a2.e

array([-0.34343762,  0.34450225, -4.79617189,  0.12096235,  0.44806666,
        0.75818924,  2.36530962,  2.59297587,  4.85687811, -2.48207469,
       -3.69682306,  2.90708493, -1.35807417,  1.38388473,  1.38660199,
       -3.51683368, -3.72375333, -3.12417953, -0.52972379,  2.67638201,
       -3.02375862,  4.74355817,  3.65005206,  0.64513397, -2.33818924,
       -0.68121752,  6.42021336, -0.449349  , -3.73113397, -0.84563499,
       -2.12878248,  1.09815058,  1.59882793,  3.1706929 ,  4.36086385,
       -5.65999967,  7.24999998,  0.60974875,  0.59134492, -1.7441906 ,
        6.51999998,  5.07999998,  6.86999998,  5.79999998,  3.21521338,
        7.64783381])

## Modify case

Basic knowledge of pwoer flow simulaiton:

1) PQ bus: give active power p, reactive power q, sovle voltage amplitude and angle

2) PV bus: give active power p, votlage amplitude, solve reactive pwoer q and votlage angle

3) Slack: give voltage amplitue = 1 and voltage angle = 0, solve active power p and reactive power q

### Modify power flow case

In [40]:
# Modify load data

# ------- Scale all loads ---------
ssa.PQ.set(
            src='p0', 
            idx= ssa.PQ.idx.v, 
            attr='v',
            value= 1.1 * ssa.PQ.p0.v
        )

ssa.PQ.set(
            src='q0', 
            idx= ssa.PQ.idx.v, 
            attr='v',
            value= 1.1 * ssa.PQ.q0.v
        )

True

In [42]:
# Change specific load based on idx
# Note: check the case (excel) file to get the correct idx
ssa.PQ.set(
            src='p0', 
            idx= ['PQ_1', 'PQ_10'], 
            attr='v',
            value= np.array([8, 4])
        )

ssa.PQ.set(
            src='q0', 
            idx= ['PQ_1', 'PQ_10'], 
            attr='v',
            value= np.array([2, 1])
        )

True

In [43]:
# change power reference of PV/Slack bus 

# PV bus
# Note: check the case (excel) file to get the correct idx
# If the idx is number, then use idx= [1, 2] instead of idx= ['1', '2']
ssa.PV.set(
            src='p0', 
            idx= [1, 2], 
            attr='v',
            value= np.array([5, 7])
        )

ssa.PV.set(
            src='q0', 
            idx= [1, 2], 
            attr='v',
            value= np.array([2, 2.5])
        )

True

In [44]:
# Slack bus
# Note: check the case (excel) file to get the correct src and idx
ssa.Slack.set(
            src='v0', 
            idx= 10, 
            attr='v',
            value= np.array([1])
        )

ssa.Slack.set(
            src='a0', 
            idx= 10, 
            attr='v',
            value= np.array([0])
        )

True

### Add new components

Note: Adding new components can only be done before setting up the case '''ssa.setup()'''

So, we will need to load a new case and work on adding new components

In [45]:
ssa = andes.load(
                andes.get_case('ieee39/ieee39.xlsx'),
                setup=False,     # If setup=False, need to call ss.setup() before running the simulation
                no_output=True, 
                default_config=False
            )

In [46]:
# Add new load
# Remove load can be done by setting the p0 and q0 to 0
ssa.add(model="PQ", param_dict=dict(bus=2, 
                                    idx="PQ_20", 
                                    p0=0.5, 
                                    q0=0.2
                                    ))

'PQ_20'

In [47]:
# We can check the all the compoennts by printing the component as dataframe
# ssa.PQ.as_df()

In [48]:
# Add new generator
# Remove generator can be done by setting the p0 and q0 to 0
ssa.add(model="PV", param_dict=dict(bus=15, 
                                    idx='15', 
                                    p0=0.5, 
                                    q0=0.2,
                                    pmax=5,
                                    pmin=0,
                                    qmax=2,
                                    qmin=-2,
                                    v0=1.0,
                                    ))

'15'

In [49]:
# We can check the all the compoennts by printing the component as dataframe
# ssa.PV.as_df()

In [50]:
ssa.setup()
ssa.PFlow.run()

c:\users\sheb691\gitpack\andes\andes\core\model\model.py:1712: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  return numba.jit(func,


True

## TODO: evaluate the new power flow results after modifying the case

## Results query and analysis 

For example:

1) How many generators/loads does the system have?

2) What is the maximum/minimum generator capacity?

3) Which bus has the highest voltage?

4) Which generator outputs the maximum/minimum power?

5) Plot ... results

# Modify case request and summarize the new reuslts

1) choose actions in the list above to modify the case -- This is usually the request from users

2) run power flow and summarize the key changes, e.g., generator output change, branch flow change, votlage change
